### ISSUE TITLE
Dockerfile question

### ISSUE THREAD

**Issue by bobhaffner** [florimondmanca/kafka-fraud-detector#1]
Hi,

First off, thank you for the great tutorial!  

I have a question regarding the Dockerfile for the generator and the detector

```
FROM python:3.6

WORKDIR /usr/app

ADD ./requirements.txt ./
RUN pip install -r requirements.txt
ADD ./ ./

CMD ["python", "app.py"]
```

Couldn't you delete `ADD ./requirements.txt ./` and move `ADD ./ ./` up before the Run Pip line since it adds all the necessary files anyway?  If I'm correct, I can submit a PR if you'd like.

Also, the blog post source is not consistent with the repo source.  See below

```
# Dockerfile
FROM python:3.7

WORKDIR /usr/app

ADD ./requirements ./
RUN pip install -r requirements.txt
ADD ./app.py ./

CMD ["python", "app.py"]
```

**Comment by florimondmanca** [comment]
Hi @bobhaffner !

I'm glad you enjoyed the tutorial. Thanks for spotting the `Dockerfile` inconsistency. The correct version is the repo one, so I've updated the post to be the same. :+1:

Concerning the `ADD ./requirements.txt ./` instruction: The reason I'm putting it before adding the rest is to make use of the Docker caching mechanism. 📦 

When building the image, (e.g. when running `docker-compose up --build`), `RUN pip install -r requirements.txt` is only executed if the `requirements.txt` file changes, otherwise a cached image is used.

This saves time during the build, which speeds up the development process overall when no dependencies have changed. 😄 

As an illustration, I force-changed `app.py` by adding a random `print()` statement. Here is the resulting build log:

```
Building generator
Step 1/6 : FROM python:3.6
 ---> 4f13b7f2138e
Step 2/6 : WORKDIR /usr/app
 ---> Using cache
 ---> 24becf2351ca
Step 3/6 : ADD ./requirements.txt ./
 ---> Using cache
 ---> 88e6f3705c79
Step 4/6 : RUN pip install -r requirements.txt
 ---> Using cache
 ---> 53c64d4f3325
Step 5/6 : ADD ./ ./
 ---> b539ca2da38c
Step 6/6 : CMD ["python", "app.py"]
 ---> Running in 215c2ee56cb0
Removing intermediate container 215c2ee56cb0
 ---> de1b4ce7ae9e
Successfully built de1b4ce7ae9e
Successfully tagged kafka-fraud-detector_generator:latest
```

As you can see, Docker is using the cache up to step 5/6. 👍 

The rules for using the cached vs. building a new container are described in the Docker docs: [Leverage the build cache](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#leverage-build-cache).

Thanks again for pointing this out! I'm closing this issue but feel free if you have any other questions.

**Comment by bobhaffner** [comment]
Thanks @florimondmanca!!
