### ISSUE TITLE
syntax issue with `transactions.py`

### ISSUE THREAD

**Issue by t-0-m-1-3** [florimondmanca/kafka-fraud-detector#2]
I'm unable to run the sample; I keep getting an invalid syntax error at the line [for `def _random_amount()`](https://github.com/florimondmanca/kafka-fraud-detector/blob/30324569f9ad13f34fd070ae0a69d464188f9caa/generator/transactions.py#L14) when i run `docker-compose` 

![image](https://user-images.githubusercontent.com/20537914/51497179-47e1fe80-1d90-11e9-81ed-3c23956224d0.png)

**Comment by florimondmanca** [comment]
Hi @t-0-m-1-3,

That's strange to me. This seems to be an issue with the type annotation, but the image is using Python 3.6 so that shouldn't be a problem. Plus, I wasn't able to replicate the issue, even when forcing `--build` on the images.

Can you check the Python version within the container, or define a type-annotated function in an interpreter within the container as a sanity check? e.g.:

```python
def foo() -> int:
    return 0
```

**Comment by t-0-m-1-3** [comment]
i swapped out 
`CMD ["python", "app.py"]`

for

`CMD["python3","app.py"]` and i was able to get past the annotated functions; 

Now i'm just on that `kafka.errors.NoBrokersAvailable` error; 

If I can't crack it I'll reach back out for help

**Comment by t-0-m-1-3** [comment]
> i swapped out
> `CMD ["python", "app.py"]`
> 
> for
> 
> `CMD["python3","app.py"]` and i was able to get past the annotated functions;
> 
> Now i'm just on that `kafka.errors.NoBrokersAvailable` error;
> 
> If I can't crack it I'll reach back out for help

i needed to start the `docker-compose.kafka.yml` before the other one and everything worked beautifully;

thanks for the great post/help

got anything else that fun to wire together?

**Comment by florimondmanca** [comment]
> i needed to start the docker-compose.kafka.yml before the other one and everything worked beautifully;

Yep, the `NoBrokersAvailable` error is one from the `kafka-python` library, indicating that the Kafka cluster cannot be reached (because it wasn't started).

Glad to hear everything worked well! I may update the `Dockerfile` to use `python3` in case other people stumble upon this issue too. :)

> thanks for the great post/help

Cheers!

> got anything else that fun to wire together?

I haven't got much time for blog posts at the moment unfortunately, but I liked writing this tutorial and would be happy to do more of this kind in the future. :)

**Comment by t-0-m-1-3** [comment]
I'll file a PR, you can merge if you want; I have it all working
